<!DOCTYPE html>
<html>
  <head>
    <title>ADDFII SSIS</title>
    <style>
      @page {
        size: A4 landscape;
        margin: 20px;
      }
      
      .styled-table {
        border-collapse: collapse;
        font-size: 0.9em;
        font-family: sans-serif;
        width: 100%;
      }
      
      .styled-table thead tr {
        text-align: left;
        border-bottom: 1px solid black;
      }
      
      .styled-table th,
      .styled-table td {
        padding: 12px 15px;
      }
      
      .styled-table tbody tr {
        border-bottom: 1px solid black;
      }
    </style>
  </head>
  <body>
    <div>
      <h3>Monthly Report</h3>
    </div>
    <table class="styled-table">
      <thead>
        <tr>
          <th>No.</th>
          <th>Date Enrolled</th>
          <th>Name</th>
          <th>Age</th>
          <th>Locale</th>
          <th>District</th>
          <th>Medical Diagnosis</th>
          <th>Medical Category</th>
          <th>Doctor in Charge</th>
          <th>Update/Status</th>
          <th>Last Date Updated</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td>{{ $client_profile_info->created_at}}</td>
          <td>{{ $client_profile_info->getFullName($client_profile_info->id) }}</td>
          <td>{{ $client_profile_info->age }}</td>
          <td>{{ $client_profile_info->locale->getLocaleName($client_profile_info->locale_id) }}</td>
          <td>{{ $client_profile_info->locale->getDistrictName($client_profile_info->locale_id) }}</td>
          {{-- <td>{{ $medical_condition->disease->getName($medical_condition->disease_id) }}</td> --}}
          <td>{{ $client_profile_info->getMedicalCategoryName($client_profile_info->medical_category_id) }}</td>
          {{-- <td>{{ $medical_condition->doctor }}</td> --}}
          <td> </td>
          <td>{{ $client_profile_info->updated_at}}</td>
        </tr>
      </tbody>
    </table>
    <div style="margin-top: 2rem">
      <div>Generated Report By: ADDFI SSIS</div>
      <div>Generated By: <span>{{ $user_info->getFullName($user_info->id) }}</span></div>
      <div>Date Generated: <span>{{ $date }}</span></div>
  </div>
  </body>
</html>
