<!DOCTYPE html>
<html>
  <head>
    <title>ADDFII SSIS</title>
    <style>
      @page {
        size: A4 landscape;
        margin: 20px;
      }
      
      .styled-table {
        border-collapse: collapse;
        font-size: 0.9em;
        font-family: sans-serif;
        width: 100%;
      }
      
      .styled-table thead tr {
        text-align: left;
        border-bottom: 1px solid black;
      }
      
      .styled-table th,
      .styled-table td {
        padding: 12px 15px;
      }
      
      .styled-table tbody tr {
        border-bottom: 1px solid black;
      }
    </style>
  </head>
  <body>
    <div>
      <h3>Monthly Report</h3>
    </div>
    <table class="styled-table">
      <thead>
        <tr>
          <th>No.</th>
          <th>Date Enrolled</th>
          <th>Name</th>
          <th>Age</th>
          <th>Locale</th>
          <th>District</th>
          <th>Medical Diagnosis</th>
          <th>Medical Category</th>
          <th>Doctor in Charge</th>
          <th>Status</th>
          <th>Last Date Updated</th>
        </tr>
      </thead>
        @foreach ($client_profiles as $client_profile_info)
          @php
            $medical_conditions_filtered = $medical_conditions->where('client_profile_id', $client_profile_info->id);
          @endphp
          <tbody>
            <tr>
              <td>{{ $client_profile_info->id}}</td>
              <td>{{ $client_profile_info->created_at}}</td>
              <td>{{ $client_profile_info->getFullName($client_profile_info->id) }}</td>
              <td>{{ $client_profile_info->age }}</td>
              <td>{{ $client_profile_info->locale->getLocaleName($client_profile_info->locale_id) }}</td>
              <td>{{ $client_profile_info->locale->getDistrictName($client_profile_info->locale_id) }}</td>
              @foreach ($medical_conditions_filtered as $medical_condition)
                <td>{{ $medical_condition->getDiseaseName($medical_condition->disease_id) }}</td> --}}
              @endforeach
              <td>{{ $client_profile_info->getMedicalCategoryName($client_profile_info->medical_category_id) }}</td>
              <td>{{ $client_profile_info->getAssignedDoctorName($client_profile_info->assigned_doctor_id) }}</td>
              <td>{{ $client_profile_info->status }}</td>
              <td>{{ $client_profile_info->dateFormatMdY($client_profile_info->updated_at)}}</td>
            </tr>
          </tbody>
        @endforeach
    </table>
    <div style="margin-top: 2rem">
      <div>Generated Report By: ADDFI SSIS</div>
      <div>Generated By: <span>{{ $user_info->getFullName($user_info->id) }}</span></div>
      <div>Date Generated: <span>{{ $date }}</span></div>
    </div>
  </body>
</html>
